version: '2'
services:
  nginx_portal2:
    image: steveltn/https-portal
    container_name: nginx_proxy_container2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl_letsen:/var/lib/https-portal
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
     DOMAINS: 'parse.iparroting.net -> http://parse_server2:1337'
     #DOMAINS: 'parse2.iparroting.net -> http://parse.iparroting.net:1337/'
     STAGE: 'production'
    networks:
      - frontend

  MongoDB:
    image: mongo
    container_name: mongo_parse
    volumes:
      - ../parse_mongo_data:/data/db
    networks:
      - backend

  parse_server2:
    build: .
    container_name: parse_server2
    environment:
      - APP_ID
      - MASTER_KEY
      - DATABASE_URI
      - SERVER_URL
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - S3_BUCKET
      - S3_DIRECT
      - VIRTUAL_HOST=parse.iparroting.net
      - VIRTUAL_PROTO=http
    volumes:
      - "./:/host"
    links:
      - MongoDB:MongoDB
    ports:
      - "1337:1337"
    networks:
      - frontend
      - backend
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
